Models/SOP/Authority.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace BLMS.Models.SOP
{
    public class Authority
    {
        [Key]
        public int AuthorityID { get; set; }

        [DisplayName("Authority Link")]
        public string AuthorityLink { get; set; }

        [DisplayName("Authority Name")]
        public string AuthorityName { get; set; }

        public string OldAuthorityLink { get; set; }

        public string OldAuthorityName { get; set; }

        public int ExistData { get; set; }

        public string UserName { get; set; }
    }
}

Controllers/AuthorityController.cs
using BLMS.Context;
using BLMS.Custom_Attributes;
using BLMS.CustomAttributes;
using BLMS.Enums;
using BLMS.Models.SOP;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using static BLMS.Helper;

namespace BLMS.Controllers
{
    public class AuthorityController : Controller
    {
        readonly SOPDBContext dbContext = new SOPDBContext();

        #region GRIDVIEW
        //[Authorize(Roles.ADMINISTRATOR, Roles.BUSINESS_UNIT, Roles.PIC)]
        //[Authorize(AccessLevel.ADMINISTRATION, AccessLevel.HQ, AccessLevel.SITE)]
        public ActionResult Index()
        {
            List<Authority> authorityList = dbContext.AuthorityGetAll().ToList();

            if (TempData["createMessage"] != null)
            {
                ViewBag.Alert = AlertNotification.ShowAlert(Alert.Success, TempData["createMessage"].ToString());
            }
            else if (TempData["editMessage"] != null)
            {
                ViewBag.Alert = AlertNotification.ShowAlert(Alert.Success, TempData["editMessage"].ToString());
            }
            else if (TempData["deleteMessage"] != null)
            {
                ViewBag.Alert = AlertNotification.ShowAlert(Alert.Delete, TempData["deleteMessage"].ToString());
            }

            return View(authorityList);
        }
        #endregion

        #region CREATE
        //[NoDirectAccess]
        public ActionResult Create()
        {
            return View();
        }

        // POST: BusinessDivController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind] Authority authority)
        {
            try
            {
                string UserName = HttpContext.User.Identity.Name;

                if (string.IsNullOrEmpty(authority.AuthorityName) && string.IsNullOrEmpty(authority.AuthorityLink))
                {
                    ModelState.AddModelError("", "Please type Authority Name");
                    ModelState.AddModelError("", "Please type Authority Link");
                    ViewBag.Alert = AlertNotification.ShowAlertAll(Alert.WarningTwo, "Please type Authority Name", "Please type Authority Link", "", "");
                }
                else if (string.IsNullOrEmpty(authority.AuthorityName))
                {
                    ModelState.AddModelError("", "Please type Authority Name");
                    ViewBag.Alert = AlertNotification.ShowAlert(Alert.Warning, "Please type Authority Name");
                }
                else if (string.IsNullOrEmpty(authority.AuthorityLink))
                {
                    ModelState.AddModelError("", "Please type Authority Link");
                    ViewBag.Alert = AlertNotification.ShowAlert(Alert.Warning, "Please type Authority Link");
                }
                else if (ModelState.IsValid)
                {
                    string AuthorityName = authority.AuthorityName;

                    Authority checkAuthority = dbContext.CheckAuthorityByName(AuthorityName);

                    if (checkAuthority.ExistData == 1)
                    {
                        ViewBag.Alert = AlertNotification.ShowAlert(Alert.Danger, string.Format("{0} already existed in BLMS database!", AuthorityName));
                        return View(authority);
                    }
                    else
                    {
                        dbContext.AddAuthority(authority, UserName);
                        TempData["createMessage"] = string.Format("{0} has been successfully created!", AuthorityName);
                        return RedirectToAction("Index");
                    }
                }

                return View(authority);
            }
            catch
            {
                return View();
            }
        }
        #endregion

        #region EDIT
        //[NoDirectAccess]
        public ActionResult Edit(int id)
        {
            Authority authority = dbContext.GetAuthorityByID(id);

            if (authority == null)
            {
                return NotFound();
            }

            return View(authority);
        }

        // POST: BusinessDivController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, [Bind] Authority authority)
        {
            try
            {
                string UserName = HttpContext.User.Identity.Name;

                if (string.IsNullOrEmpty(authority.AuthorityName) && string.IsNullOrEmpty(authority.AuthorityLink))
                {
                    ModelState.AddModelError("", "Please type Authority Name");
                    ModelState.AddModelError("", "Please type Authority Link");
                    ViewBag.Alert = AlertNotification.ShowAlertAll(Alert.WarningTwo, "Please type Authority Name", "Please type Authority Link", "", "");
                }
                else if (string.IsNullOrEmpty(authority.AuthorityName))
                {
                    ModelState.AddModelError("", "Please type Authority Name");
                    ViewBag.Alert = AlertNotification.ShowAlert(Alert.Warning, "Please type Authority Name");
                }
                else if (string.IsNullOrEmpty(authority.AuthorityLink))
                {
                    ModelState.AddModelError("", "Please type Authority Link");
                    ViewBag.Alert = AlertNotification.ShowAlert(Alert.Warning, "Please type Authority Link");
                }
                else if (ModelState.IsValid)
                {
                    Authority checkAuthority= dbContext.CheckAuthorityByName(authority.AuthorityName);

                    if (checkAuthority.ExistData == 1 && authority.AuthorityName == authority.OldAuthorityName && authority.AuthorityLink == authority.OldAuthorityLink)
                    {
                        return RedirectToAction("Index");
                    }
                    else if (checkAuthority.ExistData == 1 && authority.AuthorityName != authority.OldAuthorityName)
                    {
                        ViewBag.Alert = AlertNotification.ShowAlert(Alert.Danger, string.Format("{0} already existed in BLMS database!", authority.AuthorityName));
                        return View(authority);
                    }
                    if (checkAuthority.ExistData == 1 && (authority.AuthorityName != authority.OldAuthorityName | authority.AuthorityLink == authority.OldAuthorityLink))
                    {
                        dbContext.EditAuthority(authority, UserName);
                        TempData["editMessage"] = string.Format("{0} has been successfully edited!", authority.AuthorityName);
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        dbContext.EditAuthority(authority, UserName);
                        TempData["editMessage"] = string.Format("{0} has been successfully edited!", authority.AuthorityName);
                        return RedirectToAction("Index");
                    }
                }

                return View(dbContext);
            }
            catch
            {
                return View();
            }
        }
        #endregion

        #region DELETE
        public JsonResult Delete(int Id)
        {

            try
            {
                Authority authority = dbContext.GetAuthorityByID(Id);

                dbContext.DeleteAuthority(Id);
                TempData["deleteMessage"] = string.Format("{0} has been deleted from BLMS database!", authority.AuthorityName);

                return Json(new { status = "Success" });
            }
            catch
            {
                return Json(new { status = "Fail" });
            }
        }
        #endregion
    }
}

Views/Authority/Create.cshtml
@model BLMS.Models.SOP.Authority

@{
    ViewData["Title"] = "Authority Link";
    Layout = "~/Views/Shared/_SOPLayout.cshtml";
}

<div class="container-fluid mt-5 mt-md-0 mb-0">
    <div class="row" style="margin-top: -100px;">
        <div class="col-md-12 px-lg-5">
            <div class="card pb-5 mx-md-3">
                <div class="card-body">
                    <div class="container text-center my-5">
                        <h2 class="title font-weight-bold my-3 wow fadeIn" data-wow-delay="0.2s">
                            <strong>CREATE AUTHORITY LINK</strong>
                        </h2>

                        <p class="grey-text w-responsive mx-auto mb-3 wow fadeIn" data-wow-delay="0.2s">
                            Notes: Please fill the field to register new Authority Link.
                        </p>

                        <div class="row">
                            <div class="col-lg-12 wow fadeIn" data-wow-delay="0.2s">
                                <form asp-action="Create" autocomplete="off">
                                    <div class="row">
                                        <div class="col-md-12 text-left">
                                            <div id="alert" class="form-group" style="font-size: 14px;">
                                                @Html.Raw(@ViewBag.Alert)
                                            </div>
                                        </div>
                                    </div>

                                    <div class="row">
                                        <div class="col-md-12">
                                            <div class="form-group">
                                                <div class="md-form form-sm">
                                                    <input asp-for="AuthorityName" class="form-control" placeholder="Please type Authority Name" style="font-size: 13px;">
                                                    <label asp-for="AuthorityName" class="control-label font-weight-bold" style="font-size: 18px;"><span style="color:red;">*</span> Authority Name</label>
                                                </div>
                                            </div>

                                            <div class="form-group">
                                                <div class="md-form form-sm">
                                                    <textarea asp-for="AuthorityLink" rows="3" class="md-textarea form-control" placeholder="Please type Authority Link" style="font-size: 13px;"></textarea>
                                                    <label asp-for="AuthorityLink" class="control-label font-weight-bold" style="font-size: 18px;"><span style="color:red;">*</span> Authority Link</label>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <br />

                                    <div class="row">
                                        <div class="col-md-12 text-left">
                                            <div class="form-group">
                                                <input type="submit" value="Create" class="btn btn-outline-dark dusty-grass-gradient waves-effect font-weight-bold" style="font-size: 12px;" />
                                                <a asp-action="Index" class="btn btn-outline-dark cloudy-knoxville-gradient waves-effect font-weight-bold" style="font-size: 12px;">Back</a>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Authority/Edit.cshtml
@model BLMS.Models.SOP.Authority

@{
    ViewData["Title"] = "Authority Link";
    Layout = "~/Views/Shared/_SOPLayout.cshtml";
}

<div class="container-fluid mt-5 mt-md-0 mb-0">
    <div class="row" style="margin-top: -100px;">
        <div class="col-md-12 px-lg-5">
            <div class="card pb-5 mx-md-3">
                <div class="card-body">
                    <div class="container text-center my-5">
                        <h2 class="title font-weight-bold my-3 wow fadeIn" data-wow-delay="0.2s">
                            <strong>EDIT AUTHORITY LINK</strong>
                        </h2>

                        <p class="grey-text w-responsive mx-auto mb-3 wow fadeIn" data-wow-delay="0.2s">
                            Notes: Please change the entry to edit existing Authority Link.
                        </p>

                        <div class="row">
                            <div class="col-lg-12 wow fadeIn" data-wow-delay="0.2s">
                                <form asp-action="Edit" autocomplete="off">
                                    <div class="row">
                                        <div class="col-md-12 text-left">
                                            <div id="alert" class="form-group" style="font-size: 14px;">
                                                @Html.Raw(@ViewBag.Alert)
                                            </div>
                                        </div>
                                    </div>

                                    <input type="hidden" asp-for="AuthorityID" />
                                    <input type="hidden" asp-for="OldAuthorityLink" />
                                    <input type="hidden" asp-for="OldAuthorityName" />

                                    <div class="row">
                                        <div class="col-md-12">
                                            <div class="form-group">
                                                <div class="md-form form-sm">
                                                    <input asp-for="AuthorityName" class="form-control" placeholder="Please type Authority Name" style="font-size: 13px;">
                                                    <label asp-for="AuthorityName" class="control-label font-weight-bold" style="font-size: 18px;"><span style="color:red;">*</span> Authority Name</label>
                                                </div>
                                            </div>

                                            <div class="form-group">
                                                <div class="md-form form-sm">
                                                    <textarea asp-for="AuthorityLink" rows="3" class="md-textarea form-control" placeholder="Please type Authority Link" style="font-size: 13px;"></textarea>
                                                    <label asp-for="AuthorityLink" class="control-label font-weight-bold" style="font-size: 18px;"><span style="color:red;">*</span> Authority Link</label>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <br />

                                    <div class="row">
                                        <div class="col-md-12 text-left">
                                            <div class="form-group">
                                                <input type="submit" value="Edit" class="btn btn-outline-dark dusty-grass-gradient waves-effect font-weight-bold" style="font-size: 12px;" />
                                                <a asp-action="Index" class="btn btn-outline-dark cloudy-knoxville-gradient waves-effect font-weight-bold" style="font-size: 12px;">Back</a>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Authority/Index.cshtml
@model IEnumerable<BLMS.Models.SOP.Authority>

@{
    ViewData["Title"] = "Authority Link";
    Layout = "~/Views/Shared/_SOPLayout.cshtml";
}

<div class="container-fluid mt-5 mt-md-0 mb-0">
    <!-- Grid row -->
    <div class="row" style="margin-top: -100px;">
        <!-- Grid column -->
        <div class="col-md-12 px-lg-5">
            <!-- Card -->
            <div class="card pb-5 mx-md-3">
                <div class="card-body">
                    <div class="container text-center my-5">
                        <h2 class="title font-weight-bold my-3 wow fadeIn" data-wow-delay="0.2s">
                            <strong>AUTHORITY LINK</strong>
                        </h2>

                        <p class="grey-text w-responsive mx-auto mb-3 wow fadeIn" data-wow-delay="0.2s">
                            In this gridview, user can track Authority Link recorded in BLMS system.
                        </p>

                        <div class="row wow fadeIn" data-wow-delay="0.2s" style="font-size: 12px;">
                            <div class="col-12">
                                <div class="card">
                                    <div class="card-body">
                                        <div id="alert" class="form-group text-left" style="font-size: 14px;">
                                            @Html.Raw(@ViewBag.Alert)
                                        </div>

                                        <table id="AuthorityLink" class="table table-hover table-wrapper table-striped table-responsive-lg text-left" cellspacing="0" width="100%">
                                            <thead>
                                                <tr>
                                                    <th class="text-sm font-weight-bold col-1" style="font-size: 12px;">No.</th>
                                                    <th class="text-sm font-weight-bold col-3" style="font-size: 12px;">
                                                        @Html.DisplayNameFor(model => model.AuthorityName)
                                                    </th>
                                                    <th class="text-sm font-weight-bold" style="font-size: 12px;">
                                                        @Html.DisplayNameFor(model => model.AuthorityLink)
                                                    </th>
                                                    <th class="text-sm font-weight-bold text-center col-2" style="font-size: 12px;">Action</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                @{ int i = 1; }
                                                @foreach (var item in Model)
                                                {
                                                    <tr id="row_@item.AuthorityID">
                                                        <td class="text-sm text-center" style="font-size: 12px;">
                                                            @i
                                                        </td>
                                                        <td class="text-sm" style="font-size: 12px;">
                                                            @Html.DisplayFor(modelItem => item.AuthorityName)
                                                        </td>
                                                        <td class="text-sm font-weight-bold text-break" style="font-size: 12px;">
                                                            <a href="@item.AuthorityLink" target="_blanK">@Html.DisplayFor(modelItem => item.AuthorityLink)</a>
                                                        </td>
                                                        <td class="text-center" style="font-size: 12px;">
                                                            <a class="btn btn-outline-dark winter-neva-gradient btn-rounded btn-sm px-2" title="Edit" href="@Url.Action("Edit", "Authority", new {id=item.AuthorityID})" style="font-size: 12px;">
                                                                <i class="fas fa-pencil-alt mt-0"></i>
                                                            </a>
                                                            <a class="btn btn-outline-dark young-passion-gradient btn-rounded btn-sm px-2" title="Delete" href="#" onclick="ConfirmDelete(@item.AuthorityID)" style="font-size: 12px;">
                                                                <i class="fas fa-trash-alt mt-0"></i>
                                                            </a>
                                                        </td>
                                                    </tr>
                                                    i++;
                                                }
                                            </tbody>
                                        </table>

                                        <!--Delete bootstrap confirmation box-->
                                        <div class="modal fade top" id="delete-conformation" aria-labelledby="delete-conformation" aria-hidden="true" tabindex="-1" role="dialog">
                                            <div class="modal-dialog modal-frame modal-top modal-notify modal-danger">
                                                <div class="modal-content">
                                                    <div class="modal-header flex-column">
                                                        <div class="icon-box">
                                                            <i class="material-icons">&#xE5CD;</i>
                                                        </div>
                                                        <h4 class="modal-title w-100 font-weight-bolder text-center text-white">DELETE AUTHORITY LINK?</h4>
                                                        <br />
                                                        <p class="mb-1 align-self-sm-center text-white" style="color: red;"><i class="fas fa-exclamation-circle"></i> The saved data will be permanently deleted from BLMS database.</p>
                                                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                                    </div>
                                                    <div class="modal-footer justify-content-center">
                                                        <button type="button" class="btn btn-outline-dark winter-neva-gradient waves-effect" data-dismiss="modal">Cancel</button>
                                                        <a href="#" class="btn btn-outline-dark young-passion-gradient waves-effect" onclick="DeleteAuthority()">Delete</a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                        <input type="hidden" id="hidAuthorityId" />

                                        <a asp-action="Create" class="btn btn-outline-dark tempting-azure-gradient btn-block text-white text-sm font-weight-bold" style="font-size: 12px;">Create Authority Link</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section CSS{
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">

    <link href="~/mdb/css/addons/datatables.min.css" rel="stylesheet" />
    <link href="~/mdb/css/addons/datatables-select.min.css" rel="stylesheet" />

    <style>
        .select-wrapper input.select-dropdown {
            font-size: 12px;
        }

        .dropdown-content li > span {
            font-size: 12px;
        }
    </style>
}

@section Scripts {
    <script>
        new WOW().init();

        var ConfirmDelete = function (AuthorityId) {

            $("#hidAuthorityId").val(AuthorityId);
            $("#delete-conformation").modal('show');
        }

        var DeleteAuthority = function () {
            var AuthorityId = $("#hidAuthorityId").val();

            $.ajax({
                type: "POST",
                url: '@Url.Action("Delete", "Authority")',
                dataType: "json",
                data: { Id: AuthorityId },
                success: function (result) {
                    $("#delete-conformation").modal("hide");
                    $("#row_" + AuthorityId).remove();
                    window.location.href =  '@Url.Action("Index", "Authority")'
                }
            })
        }

        $(document).ready(function () {
            $('#AuthorityLink').DataTable();
            $('#AuthorityLink_wrapper').find('label').each(function () {
                $(this).parent().append($(this).children());
            });
            $('#AuthorityLink_wrapper .dataTables_filter').find('input').each(function () {
                $('input').attr("placeholder", "Search");
                $('input').attr("style", 'font-size: 12px');
                $('input').removeClass('form-control-sm');
            });
            $('#AuthorityLink_wrapper .dataTables_length').addClass('d-flex flex-row');
            $('#AuthorityLink_wrapper .dataTables_filter').addClass('md-form');
            $('#AuthorityLink_wrapper select').removeClass(
                'custom-select custom-select-sm form-control form-control-sm');
            $('#AuthorityLink_wrapper select').addClass('mdb-select');
            $('#AuthorityLink_wrapper .mdb-select').materialSelect();
            $('#AuthorityLink_wrapper .dataTables_filter').find('label').remove();
        });

        //auto hide viewbag.alert
        $(document).ready(function () {
            setTimeout(function () {
                $("#alert").fadeOut();
            }, 3000);
        });
    </script>

    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}